# -*- coding: utf-8 -*-
"""IFN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PCEjw18ErA5U_bD6LfGvVgsA29vEKziV
"""

#Albert Yesid Rey Contreras 01240372016
#Diego Fernando Rojas Arce 01240372034
import ipywidgets as wd
from IPython.display import display
import pandas as pd
from google.colab import files

#titulo y estilo de los campos de entrada
titulo = wd.HTML("<h1>INVENTARIO FORESTAL</h1>")
style = {'description_width': '130px'}

#Listas
datos_fauna = []
datos_flora = []

#botones iniciales
botonFauna = wd.Button(description = "FAUNA", button_style = "primary")
botonFlora = wd.Button(description = "FLORA", button_style = 'success')
botonDatos = wd.Button(description = "MOSTRAR DATOS", button_style = "info")
f1 = wd.HBox([botonFauna, botonFlora, botonDatos])

#botones para cuando haya algun dato guardado
botonEditar = wd.Button(description = "EDITAR")
botonEliminar = wd.Button(description = "ELIMINAR", button_style = "danger")
botonDescargar = wd.Button(description = "DESCARGAR", button_style = "success")
#ocultar estos tres botones desde el principio
f2 = wd.HBox([botonEditar, botonEliminar, botonDescargar])
f2.layout.display = 'none'

#caja de salida
salida = wd.Output()

#funciones
def mostrarBotones():
  if len(datos_fauna) > 0 or len(datos_flora) > 0:
    f2.layout.display = ''
  else:
    f2.layout.display = 'none'

def fauna(b):
    salida.clear_output()
    with salida:
      print("-"*15,"Animales","-"*15)
      brigada = wd.IntText(description="Número# Brigada:", style = style)
      conglomerado = wd.Dropdown(description="Conglomerado:", options=["Caribe", "Andina", "Pacífico", "Orinoquía", "Amazonas"], style = style)
      codigoId = wd.IntText(description="Código ID:", style = style)
      nombre = wd.Text(description="Nombre común:", style = style)
      cantidad = wd.IntText(description = "Cantidad:", style = style)
      nombreCientifico = wd.Text(description="Nombre científico:", style = style)
      tipoAnimal = wd.Dropdown(description="Tipo de animal:", options=["Mamífero","Ave", "Pez", "Reptil", "Anfibio","Invertebrado","Otro"], style = style)

      #boton para guardar los datos
      botonGuardar = wd.Button(description="Guardar", button_style="warning")
      mensaje = wd.Output()

      def guardar_fauna(b):
        mensaje.clear_output()
        with mensaje:
          if brigada.value == 0 or codigoId.value == 0 or nombre.value == '' or cantidad.value == '' or nombreCientifico.value == '':
            print(f"Ingrese valores en todos los campos para continuar.")
            return
          else:
            datos_fauna.append({
                "Brigada": brigada.value,
                "Conglomerado": conglomerado.value,
                "Id": codigoId.value,
                "Nombre": nombre.value,
                "Nombre_cientifico": nombreCientifico.value,
                "Cantidad": cantidad.value,
                "Tipo": tipoAnimal.value
            })

            #limpiar los campos de entrada después de guardar
            brigada.value = 0
            codigoId.value = 0
            nombre.value = ''
            cantidad.value = 0
            nombreCientifico.value = ''
            mostrarBotones()
            print(f"Ha sido guardado correctamente.")

      botonGuardar.on_click(guardar_fauna)
      display(wd.VBox([brigada, conglomerado, codigoId, nombre, nombreCientifico, tipoAnimal, cantidad, botonGuardar, mensaje]))

def flora(b):
  salida.clear_output()
  with salida:
    print("-"*12,"Plantas/Árboles","-"*11)
    brigada = wd.IntText(description="Número# Brigada:", style = style)
    codigoId = wd.IntText(description="Código ID:", style = style)
    conglomerado = wd.Dropdown(description="Conglomerado:", options=["Caribe", "Andina", "Pacífico", "Orinoquía", "Amazonas"], style = style)
    nombre = wd.Text(description="Nombre común:", style = style)
    nombreCientifico = wd.Text(description="Nombre científico:", style = style)
    cantidad = wd.IntText(description = "Cantidad:", style = style)
    tipoArbol = wd.Dropdown(description="Tipo de árbol:", options=["Fustales", "Latizales", "Brinzales"], style = style)
    propiedades = wd.Dropdown(description = "Propiedades:", options = ["Tóxico", "Medicinal", "Alimenticio", "Maderable"], style = style)

    #boton guardar y limpiar cada mensaje
    botonGuardar = wd.Button(description="Guardar", button_style="warning")
    mensaje = wd.Output()

    def guardar_flora(b):
      mensaje.clear_output()
      with mensaje:
        if brigada.value == 0 or codigoId.value == 0 or nombre.value == '' or cantidad.value == '' or nombreCientifico.value == '':
          print(f"Ingrese valores en todos los campos para continuar.")
          return
        else:
          datos_flora.append({
              "Brigada": brigada.value,
              "Conglomerado": conglomerado.value,
              "Id": codigoId.value,
              "Nombre": nombre.value,
              "Nombre_cientifico": nombreCientifico.value,
              "Cantidad": cantidad.value,
              "Tipo": tipoArbol.value,
              "Propiedades": propiedades.value
          })

          #limpiar campos después de guardar
          brigada.value = 0
          codigoId.value = 0
          nombre.value = ''
          cantidad.value = 0
          nombreCientifico.value = ''
          mostrarBotones()
          print(f"Ha sido guardado correctamente.")

    botonGuardar.on_click(guardar_flora)
    display(wd.VBox([brigada, conglomerado, codigoId, nombre, nombreCientifico, tipoArbol, propiedades, cantidad, botonGuardar, mensaje]))

def mostrarDatos(b):
  salida.clear_output()
  with salida:
    if len(datos_fauna) == 0 and len(datos_flora) == 0:
      print("No hay datos en fauna ni en flora.")
      return
    #fauna
    if len(datos_fauna) > 0:
      display(wd.HTML("<h1>Datos Fauna</h1>"))
      display(pd.DataFrame(datos_fauna))
    else:
      print("\nNo hay datos de fauna.")
    #flora
    if len(datos_flora) > 0:
      display(wd.HTML("<h1>Datos Flora</h1>"))
      display(pd.DataFrame(datos_flora))
    else:
      print("\nNo hay datos de flora.")

def editarDatos(b):
  salida.clear_output()
  with salida:
      print("\nIngrese el Código ID del registro a editar:")
      id = wd.IntText(description="Código ID a editar:", style=style)
      botonBuscar = wd.Button(description="BUSCAR", button_style="info")
      mensaje = wd.Output()

      def buscar_registro(b):
        mensaje.clear_output()
        with mensaje:
          #Buscar en fauna
          for i, registro in enumerate(datos_fauna):
            if registro["Id"] == id.value:
              print("Id encontrado....")
              return

          #Buscar en flora
          for i, registro in enumerate(datos_flora):
            if registro["Id"] == id.value:
              print("Id encontrado....")
              return

      botonBuscar.on_click(buscar_registro)
      display(wd.VBox([id, botonBuscar, mensaje]))

def eliminar(b):
  salida.clear_output()
  with salida:
    print("\nIngrese el ID del registro a eliminar:")
    id = wd.IntText(description = "Codigo ID a eliminar:", style = style)
    botonBuscar = wd.Button(description = "BUSCAR", button_style = "info")
    mensaje = wd.Output()

    def buscarId(b):
      mensaje.clear_output()
      with mensaje:
        if id.value == 0:
          print("\nIngrese el ID para continuar.")
          return

        #eliminar un registro guardado en fauna
        for i, registro in enumerate(datos_fauna):
          if registro["Id"] == id.value:
            borrar = datos_fauna.pop(i)
            mostrarBotones()
            print("Su registro ha sido borrado correctamente.")
            return

        #elminiar un registro guardado en flora
        for i, registro in enumerate(datos_flora):
          if registro["Id"] == id.value:
            borrar = datos_flora.pop(i)
            mostrarBotones()
            print(f"Su registro con codigo ID {borrar} ha sido eliminado correctamente.")
            return

        print(f"ID: {id.value} no econtrado, verifique y vuelva a intentar.")
        id.value = 0

    botonBuscar.on_click(buscarId)
    display(wd.VBox([id,botonBuscar, mensaje]))

botonEliminar.on_click(eliminar)
botonFauna.on_click(fauna)
botonFlora.on_click(flora)
botonDatos.on_click(mostrarDatos)
botonEditar.on_click(editarDatos)

display(titulo, f1, f2, salida)