# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PCEjw18ErA5U_bD6LfGvVgsA29vEKziV
"""

#Albert Yesid Rey Contreras 01240372016
#Diego Fernando Rojas Arce 01240372034
from typing import Optional
import ipywidgets as wd
from IPython.display import display
import pandas as pd
from google.colab import files

#titulo y estilo de los campos de entrada
titulo = wd.HTML("<h1>INVENTARIO FORESTAL</h1>")
style = {'description_width': '130px'}

#diccionarios
datos_fauna = []
datos_flora = []

#botones
botonFauna = wd.Button(description = "FAUNA", button_style = "primary")
botonFlora = wd.Button(description = "FLORA", button_style = 'success')
f1 = wd.HBox([botonFauna, botonFlora])

#caja de salida
salida = wd.Output()

#funciones
def fauna(b):
    salida.clear_output()
    with salida:
      print("-"*15,"Animales","-"*15)
      brigada = wd.IntText(description="Número# Brigada:", style = style)
      conglomerado = wd.Dropdown(description="Conglomerado:", options=["Caribe", "Andina", "Pacífica", "Orinoquía", "Amazonas"], style = style)
      codigoID = wd.Text(description="Código ID:", style = style)
      nombre = wd.Text(description="Nombre común:", style = style)
      cantidad = wd.IntText(description = "Cantidad:", style = style)
      nombreCientifico = wd.Text(description="Nombre científico:", style = style)
      tipoAnimal = wd.Dropdown(description="Tipo de animal:", options=["Mamífero","Ave", "Pez", "Reptil", "Anfibio","Invertebrado","Otro"], style = style)

      botonGuardar = wd.Button(description="Guardar", button_style="warning")
      def guardar_fauna(b):
        if brigada.value == 0 or codigoID.value == '' or nombre.value == '' or cantidad.value == '' or nombreCientifico.value == '':
          print(f"Ingrese valores en todos los campos para continuar.")
          return
        else:
          datos_fauna.append({
              "brigada": brigada.value,
              "conglomerado": conglomerado.value,
              "codigo": codigoID.value,
              "nombre": nombre.value,
              "cantidad": cantidad.value,
              "Nombre cientifico": nombreCientifico.value,
              "tipo": tipoAnimal.value
          })
          #limpiar campos después de guardar
          brigada.value = 0
          codigoID.value = ''
          nombre.value = ''
          cantidad.value = 0
          nombreCientifico.value = ''
          print(f"Ha sido guardado correctamente.")

      botonGuardar.on_click(guardar_fauna)
      display(wd.VBox([brigada, conglomerado, codigoID, nombre, nombreCientifico, tipoAnimal, cantidad, botonGuardar]))

def flora(b):
  salida.clear_output()
  with salida:
    print("-"*12,"Plantas/Árboles","-"*11)
    brigada = wd.IntText(description="Número# Brigada:", style = style)
    codigoID = wd.Text(description="Código ID:", style = style)
    conglomerado = wd.Dropdown(description="Conglomerado:", options=["Caribe", "Andina", "Pacífica", "Orinoquía", "Amazonas"], style = style)
    nombre = wd.Text(description="Nombre común:", style = style)
    nombreCientifico = wd.Text(description="Nombre científico:", style = style)
    cantidad = wd.IntText(description = "Cantidad:", style = style)
    tipoArbol = wd.Dropdown(description="Tipo de árbol:", options=["Fustales", "Latizales", "Brinzales"], style = style)
    uso = wd.Dropdown(description = "Uso", options = ["Tóxico", "Medicinal", "Alimenticio", "Maderable"], style = style)

    botonGuardar = wd.Button(description="Guardar", button_style="warning")
    def guardar_flora(b):
      if brigada.value == 0 or codigoID.value == '' or nombre.value == '' or cantidad.value == '' or nombreCientifico.value == '':
        print(f"Ingrese valores en todos los campos para continuar.")
        return
      else:
        datos_flora.append({
            "brigada": brigada.value,
            "conglomerado": conglomerado.value,
            "codigo": codigoID.value,
            "nombre": nombre.value,
            "cantidad": cantidad.value,
            "Nombre cientifico": nombreCientifico.value,
            "tipo": tipoArbol.value,
            "uso": uso.value
        })
        #limpiar campos después de guardar
        brigada.value = 0
        codigoID.value = ''
        nombre.value = ''
        cantidad.value = 0
        nombreCientifico.value = ''
        print(f"Ha sido guardado correctamente.")

    botonGuardar.on_click(guardar_flora)
    display(wd.VBox([brigada, conglomerado, codigoID, nombre, nombreCientifico, tipoArbol, uso, cantidad, botonGuardar]))

def mostrar_fauna(b):
  print()

botonFauna.on_click(fauna)
botonFlora.on_click(flora)

display(titulo, f1, salida)