# -*- coding: utf-8 -*-
"""IFN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PCEjw18ErA5U_bD6LfGvVgsA29vEKziV
"""

#Albert Yesid Rey Contreras 01240372016
#Diego Fernando Rojas Arce 01240372034
import ipywidgets as wd
from IPython.display import display
import pandas as pd
from google.colab import files

#titulo y estilo de los campos de entrada
titulo = wd.HTML("<h1>INVENTARIO FORESTAL</h1>")
style = {'description_width': '130px'}

#Listas
datos_fauna = []
datos_flora = []

#botones iniciales
botonFauna = wd.Button(description = "FAUNA", button_style = "primary")
botonFlora = wd.Button(description = "FLORA", button_style = 'success')
botonDatos = wd.Button(description = "MOSTRAR DATOS", button_style = "info")
f1 = wd.HBox([botonFauna, botonFlora, botonDatos])

#botones para cuando haya algun dato guardado
botonEditar = wd.Button(description = "EDITAR", button_style = "warning")
botonEliminar = wd.Button(description = "ELIMINAR", button_style = "danger")
botonDescargar = wd.Button(description = "DESCARGAR", button_style = "success")

#ocultar estos tres botones desde el principio
f2 = wd.HBox([botonEditar, botonEliminar, botonDescargar])
f2.layout.display = 'none'

#caja de salida
salida = wd.Output()

#funciones
def mostrarBotones():
  if len(datos_fauna) > 0 or len(datos_flora) > 0:
    f2.layout.display = ''
  else:
    f2.layout.display = 'none'

def fauna(b):
    salida.clear_output()
    with salida:
      print("-"*15,"Animales","-"*15)
      #campos de entrada
      brigada = wd.IntText(description="Número Brigada:", style = style)
      conglomerado = wd.Dropdown(description="Conglomerado:", options=["Escoge una opción","Caribe", "Andina", "Pacífico", "Orinoquía", "Amazonas"], style = style)
      codigoId = wd.IntText(description="Código ID:", style = style)
      nombre = wd.Text(description="Nombre común:", style = style)
      cantidad = wd.IntText(description = "Cantidad:", style = style)
      nombreCientifico = wd.Text(description="Nombre científico:", style = style)
      tipoAnimal = wd.Dropdown(description="Tipo de animal:", options=["Escoge una opción", "Mamífero","Ave", "Pez", "Reptil", "Anfibio","Invertebrado","Otro"], style = style)

      #boton para guardar los datos
      botonGuardar = wd.Button(description="Guardar", button_style="warning")
      mensaje = wd.Output()

      def guardar_fauna(b):
        mensaje.clear_output()
        with mensaje:

          #validaciones de ID unico en datos(fauna y flora)
          #validacion en fauna
          for registro in datos_fauna:
            if registro["Id"] == codigoId.value:
              print(f"El ID: {codigoId.value} ya existe en fauna, asigne un ID único.")
              codigoId.value = 0
              return
          #validacion en flora
          for registro in datos_flora:
            if registro["Id"] == codigoId.value:
              print(f"El ID: {codigoId.value} ya existe en flora, asigne un ID único.")
              codigoId.value = 0
              return

          if brigada.value == 0 or codigoId.value == 0 or nombre.value == '' or nombreCientifico.value == '':
            print(f"Ingrese valores en todos los campos para continuar.")
            return
          elif brigada.value <= 0 or codigoId.value < 0 or cantidad.value <= 0:
            print(f"Ingrese valores positivos para continuar")
            return
          elif conglomerado.value == "Escoge una opción" or tipoAnimal.value == "Escoge una opción":
            print("Por favor seleccione una opción en cada una de las litas desplegables.")
            return
          else:
            datos_fauna.append({
                "Brigada": brigada.value,
                "Conglomerado": conglomerado.value,
                "Id": codigoId.value,
                "Nombre": nombre.value,
                "Nombre_cientifico": nombreCientifico.value,
                "Cantidad": cantidad.value,
                "Tipo": tipoAnimal.value
            })

            #limpiar los campos de entrada después de guardar
            brigada.value = 0
            codigoId.value = 0
            nombre.value = ''
            cantidad.value = 0
            nombreCientifico.value = ''
            mostrarBotones()
            print(f"Ha sido guardado correctamente.")

      botonGuardar.on_click(guardar_fauna)
      display(wd.VBox([brigada, conglomerado, codigoId, nombre, nombreCientifico, tipoAnimal, cantidad, botonGuardar, mensaje]))

def flora(b):
  salida.clear_output()
  with salida:
    print("-"*15,"Árboles","-"*15)
    #campos de entrada
    brigada = wd.IntText(description="Número Brigada:", style = style)
    codigoId = wd.IntText(description="Código ID:", style = style)
    conglomerado = wd.Dropdown(description="Conglomerado:", options=["Escoge una opción", "Caribe", "Andina", "Pacífico", "Orinoquía", "Amazonas"], style = style)
    nombre = wd.Text(description="Nombre común:", style = style)
    nombreCientifico = wd.Text(description="Nombre científico:", style = style)
    cantidad = wd.IntText(description = "Cantidad:", style = style)
    tipoArbol = wd.Dropdown(description="Tipo de árbol:", options=["Escoge una opción", "Fustales", "Latizales", "Brinzales"], style = style)
    propiedades = wd.Dropdown(description = "Propiedades:", options = ["Escoge una opción", "Tóxico", "Medicinal", "Alimenticio", "Maderable"], style = style)

    #boton guardar y limpiar cada mensaje
    botonGuardar = wd.Button(description="Guardar", button_style="warning")
    mensaje = wd.Output()

    def guardar_flora(b):
      mensaje.clear_output()
      with mensaje:

        #validaciones de ID unico en datos(fauna y flora)
        #validacion en fauna
        for registro in datos_fauna:
          if registro["Id"] == codigoId.value:
            print(f"El ID: {codigoId.value} ya existe en fauna, asigne un ID único.")
            codigoId.value = 0
            return
        #validacion en flora
        for registro in datos_flora:
          if registro["Id"] == codigoId.value:
            print(f"El ID: {codigoId.value} ya existe en flora, asigne un ID único.")
            codigoId.value = 0
            return

        if brigada.value == 0 or codigoId.value == 0 or nombre.value == '' or nombreCientifico.value == '':
          print(f"Ingrese valores en todos los campos para continuar.")
          return
        elif brigada.value <= 0 or codigoId.value < 0 or cantidad.value <= 0:
          print(f"Ingrese valores positivos para continuar")
          return
        elif conglomerado.value == "Escoge una opción" or tipoArbol.value == "Escoge una opción" or propiedades.value == "Escoge una opción":
          print("Por favor seleccione una opción en cada una de las litas desplegables.")
          return
        else:
          datos_flora.append({
              "Brigada": brigada.value,
              "Conglomerado": conglomerado.value,
              "Id": codigoId.value,
              "Nombre": nombre.value,
              "Nombre_cientifico": nombreCientifico.value,
              "Cantidad": cantidad.value,
              "Tipo": tipoArbol.value,
              "Propiedades": propiedades.value
          })

          #limpiar campos después de guardar
          brigada.value = 0
          codigoId.value = 0
          nombre.value = ''
          cantidad.value = 0
          nombreCientifico.value = ''
          mostrarBotones()
          print(f"Ha sido guardado correctamente.")

    botonGuardar.on_click(guardar_flora)
    display(wd.VBox([brigada, conglomerado, codigoId, nombre, nombreCientifico, tipoArbol, propiedades, cantidad, botonGuardar, mensaje]))

def mostrarDatos(b):
  salida.clear_output()
  with salida:
    if len(datos_fauna) == 0 and len(datos_flora) == 0:
      print("No hay datos en fauna ni en flora.")
      return
    #fauna
    if len(datos_fauna) > 0:
      display(wd.HTML("<h1>Datos Fauna</h1>"))
      display(pd.DataFrame(datos_fauna))
    else:
      print("\nNo hay datos de fauna.")
    #flora
    if len(datos_flora) > 0:
      display(wd.HTML("<h1>Datos Flora</h1>"))
      display(pd.DataFrame(datos_flora))
    else:
      print("\nNo hay datos de flora.")

def editarDatos(b):
  salida.clear_output()
  with salida:
      print("\nIngrese el Código ID del registro a editar:")
      id = wd.IntText(description="Código ID a editar:", style=style)
      botonBuscar = wd.Button(description="BUSCAR", button_style="info")
      mensaje = wd.Output()

      def buscar_registro(b):
        mensaje.clear_output()
        with mensaje:
          #Buscar en fauna
          for i, registro in enumerate(datos_fauna):
            if registro["Id"] == id.value:
              print(f"Registro ID: {registro['Id']} encontrado en FAUNA.")
              print("\nRegistro a continuación:")
              display(pd.DataFrame([datos_fauna[i]]))

              print("\nIngrese los nuevos valores a actualizar:")
              print("-"*15,"Animales","-"*15)
              nuevo_brigada = wd.IntText(description="Número Brigada:", style = style)
              nuevo_conglomerado = wd.Dropdown(description="Conglomerado:", options=["Escoge una opción","Caribe", "Andina", "Pacífico", "Orinoquía", "Amazonas"], style = style)
              nuevo_nombre = wd.Text(description="Nombre común:", style = style)
              nuevo_cantidad = wd.IntText(description = "Cantidad:", style = style)
              nuevo_nombreCientifico = wd.Text(description="Nombre científico:", style = style)
              nuevo_tipoAnimal = wd.Dropdown(description="Tipo de animal:", options=["Escoge una opción", "Mamífero","Ave", "Pez", "Reptil", "Anfibio","Invertebrado","Otro"], style = style)

              botonActualizar = wd.Button(description = "ACTUALIZAR", button_style = "primary")
              msj = wd.Output()
              def actualizar(b):
                msj.clear_output()
                with msj:
                  #validaciones para que no hayan campos vacios
                  if nuevo_brigada.value <= 0 or nuevo_cantidad.value <= 0:
                    print("Ingrese valores positivos para continuar")
                    return
                  elif nuevo_conglomerado.value == "Escoge una opción" or nuevo_tipoAnimal.value == "Escoge una opción":
                    print("Por favor seleccione una opción en cada una de las litas desplegables.")
                    return
                  elif nuevo_nombre.value == '' or nuevo_nombreCientifico.value == '':
                    print("Ingrese los nombres de la especie a para continuar.")
                    return
                  else:
                    datos_fauna[i]["Brigada"] = nuevo_brigada.value
                    datos_fauna[i]["Conglomerado"] = nuevo_conglomerado.value
                    datos_fauna[i]["Nombre"] = nuevo_nombre.value
                    datos_fauna[i]["Nombre_cientifico"] = nuevo_nombreCientifico.value
                    datos_fauna[i]["Tipo"] = nuevo_tipoAnimal.value
                    datos_fauna[i]["Cantidad"] = nuevo_cantidad.value
                    print("\nDatos actualizados correctamente. Los puede ver en MOSTRAR DATOS")

              botonActualizar.on_click(actualizar)
              display(wd.VBox([nuevo_brigada, nuevo_conglomerado, nuevo_nombre, nuevo_nombreCientifico, nuevo_tipoAnimal, nuevo_cantidad, botonActualizar,msj]))
              return

          #Buscar en flora
          for i, registro in enumerate(datos_flora):
            if registro["Id"] == id.value:
              print(f"Registro ID: {registro['Id']} encontrado en FLORA.")
              print("\nRegistro a continuación:")
              display(pd.DataFrame([datos_flora[i]]))

              print("\nIngrese los nuevos valores a actualizar:")
              print("-"*15,"Árboles","-"*15)
              nuevo_brigada = wd.IntText(description="Número Brigada:", style = style)
              nuevo_conglomerado = wd.Dropdown(description="Conglomerado:", options=["Escoge una opción", "Caribe", "Andina", "Pacífico", "Orinoquía", "Amazonas"], style = style)
              nuevo_nombre = wd.Text(description="Nombre común:", style = style)
              nuevo_nombreCientifico = wd.Text(description="Nombre científico:", style = style)
              nuevo_cantidad = wd.IntText(description = "Cantidad:", style = style)
              nuevo_tipoArbol = wd.Dropdown(description="Tipo de árbol:", options=["Escoge una opción", "Fustales", "Latizales", "Brinzales"], style = style)
              nuevo_propiedades = wd.Dropdown(description = "Propiedades:", options = ["Escoge una opción", "Tóxico", "Medicinal", "Alimenticio", "Maderable"], style = style)

              botonActualizar = wd.Button(description = "ACTUALIZAR", button_style = "primary")
              msj = wd.Output()

              def actualizar(b):
                msj.clear_output()
                with msj:
                  #validaciones para no puedan haber campos vacios
                  if nuevo_brigada.value <= 0 or nuevo_cantidad.value <= 0:
                    print("Ingrese valores positivos para continuar.")
                    return
                  elif nuevo_conglomerado.value == "Escoge una opción" or nuevo_tipoArbol.value == "Escoge una opción" or nuevo_propiedades.value == "Escoge una opción":
                    print("Por favor seleccione una opción en cada una de las litas desplegables.")
                    return
                  elif nuevo_nombre.value == '' or nuevo_nombreCientifico.value == '':
                    print("Ingrese los nombres de la especie a para continuar.")
                    return
                  else:
                    datos_flora[i]["Brigada"] = nuevo_brigada.value
                    datos_flora[i]["Conglomerado"] = nuevo_conglomerado.value
                    datos_flora[i]["Nombre"] = nuevo_nombre.value
                    datos_flora[i]["Nombre_cientifico"] = nuevo_nombreCientifico.value
                    datos_flora[i]["Tipo"] = nuevo_tipoArbol.value
                    datos_flora[i]["Propiedades"] = nuevo_propiedades.value
                    datos_flora[i]["Cantidad"] = nuevo_cantidad.value
                    print(f"\nDatos actualizados correctamente. Los puede ver en MOSTRAR DATOS.")

              botonActualizar.on_click(actualizar)
              display(wd.VBox([nuevo_brigada, nuevo_conglomerado, nuevo_nombre, nuevo_nombreCientifico, nuevo_tipoArbol, nuevo_propiedades, nuevo_cantidad, botonActualizar, msj]))
              return

          print(f"ID {id.value} no encontrado. Verifique el ID en Mostrar datos.")
          id.value = 0

      botonBuscar.on_click(buscar_registro)
      display(wd.VBox([id, botonBuscar, mensaje]))

def eliminar(b):
  salida.clear_output()
  with salida:
    print("\nIngrese el ID del registro a eliminar:")
    print()
    id = wd.IntText(description = "Codigo ID a eliminar:", style = style)
    botonBuscar = wd.Button(description = "BUSCAR", button_style = "info")
    mensaje = wd.Output()

    def buscarId(b):
      mensaje.clear_output()
      with mensaje:
        if id.value == 0:
          print("Ingrese el ID para continuar.")
          return

        #eliminar un registro guardado en fauna
        for i, registro in enumerate(datos_fauna):
          if registro["Id"] == id.value:
            borrar = datos_fauna.pop(i)
            mostrarBotones()
            print(f"Su registro con codigo ID: {registro['Id']} ha sido eliminado correctamente.")
            print("\nRegistro elminado:")
            display(pd.DataFrame([borrar]))
            return

        #elminiar un registro guardado en flora
        for i, registro in enumerate(datos_flora):
          if registro["Id"] == id.value:
            borrar = datos_flora.pop(i)
            mostrarBotones()
            print(f"Su registro con codigo ID: {registro['Id']} ha sido eliminado correctamente.")
            print("\nRegistro elminado:")
            display(pd.DataFrame([borrar]))
            return

        print(f"ID: {id.value} no econtrado. Verifique el ID en Mostrar datos.")
        id.value = 0

    botonBuscar.on_click(buscarId)
    display(wd.VBox([id,botonBuscar, mensaje]))

botonFauna.on_click(fauna)
botonFlora.on_click(flora)
botonDatos.on_click(mostrarDatos)
botonEditar.on_click(editarDatos)
botonEliminar.on_click(eliminar)

display(titulo, f1, f2, salida)